name: Unit Tests
run-name: Run Unit Tests
on:
  push:
    branches-ignore:
      - 'main'
      - 'dev'
jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: |
          chmod +x ./test/unit-test.sh
          ./test/unit-test.sh
        shell: bash
